name: lint_and_tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.8]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade 'pip>=22.1.2'
        python -m pip show pip
        python -m pip install -e '.[dependencies]'
        
    - name: isort
      run: isort --check --diff .
    - name: black
      run: black --check --diff .
    - name: pytest
      run: pytest laser_encoders
